version: "3.9"

services:
  redis:
    image: redis:7
    container_name: litellm-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9999:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3333:3000"
    depends_on:
      - prometheus
volumes:
  redis_data:


